### PR TITLE
refactor(constants): set confirmed_bag_alerts to const

### PR DESCRIPTION
**Pull request by naeruru**
**Please describe the changes this PR makes and why it should be merged:**

This merge changes `confirmed_bag_alerts` to a const, as the variable is located in the constants folder and is also never reassigned, only referenced.

### CODE REVIEW

**Comment by ben-rube** [comment]
wow what a great change! Only a fool would use let instead of const!

**Comment by kmbass** [comment]
Screenshot_20220411-143530_Discord

**Comment by dabass2** [comment]
> wow what a great change! Only a fool would use let instead of const!

Hi ben-rube,

We appreciate your feedback on the major-bag-alert API but please keep the comments a friendly and respectful place that aides in facilitating useful dialogue.

**Comment by dabass2** [comment]
> **Please describe the changes this PR makes and why it should be merged:**
> 
> This merge changes `confirmed_bag_alerts` to a const, as the variable is located in the constants folder and is also never reassigned, only referenced.

Great suggestion! This must've been missed when updating the data types.

Thanks much! I'll merge this ASAP.

**Pull request merged**
